$root = 'D:\AEP-Authentication-Enablement-Platform\aep-client'
$files = @('aep-auth.js', 'aep-guard.js', 'aep-signin.js')
$lines = @()
$lines += '/* AUTOGENERATED by rebuild-assets.js — do not edit by hand.'
$lines += ' * Re-run "npm run rebuild-assets" to refresh from browser/*.js sources. */'
$lines += "'use strict';"
$lines += ''
$exports = @()
foreach ($f in $files) {
  $key = ($f -replace '\.js$','_JS').ToUpper().Replace('-','_')
  $bytes = [System.IO.File]::ReadAllBytes((Join-Path $root (Join-Path 'browser' $f)))
  $b64 = [Convert]::ToBase64String($bytes)
  $varName = $key
  $lines += "const $varName = Buffer.from('$b64', 'base64').toString('utf8');"
  $lines += ''
  $exports += $varName
}
$lines += 'module.exports = { ' + ($exports -join ', ') + ' };'
$lines += ''
$out = $lines -join "`n"
[System.IO.File]::WriteAllText((Join-Path $root 'assets.js'), $out, [System.Text.Encoding]::UTF8)
Write-Output "Wrote assets.js: $((Get-Item (Join-Path $root 'assets.js')).Length) bytes"
